### PR TITLE
Add the language Simplified Chinese

### PR DESCRIPTION
**Pull request by Chiloven945**

### CODE REVIEW

**Comment by Superkat32** [comment]
Thank you!

Do you want credit in the `fabric.mod.json` as a contributor?

**Comment by Chiloven945** [comment]
No, thanks <3

**Comment by Superkat32** [comment]
Sounds good! I'll try and get this pushed soon. Thanks again!

**Comment by Superkat32** [comment]
Sorry for the very long delay, I've been really busy. Hoping to get this all released today though. Once again, thank you so much!

**Pull request merged**
